### ISSUE TITLE
Vectr is closed source

### ISSUE THREAD

**Issue by jordanpotti** [ch33r10/EnterprisePurpleTeaming#1]
Awesome collection of resources :) One thing worth calling out is that Vectr is a closed source tool. It is free but I think its worth calling out that the source is not open or available. 

````
VECTR by Security Risk Advisors - Link
TALK: Red Team Exercise Closure and Showing Value with VECTR with Jorge Orchilles - Link
````

**Comment by ch33r10** [comment]
Updated the header for that section to FREE-ISH instead of open source
