### ISSUE TITLE
Presentation for Consideration

### ISSUE THREAD

**Issue by ssnkhan** [ch33r10/EnterprisePurpleTeaming#2]
Hello,

I wondered whether my talk on [Adversarial Threat Modelling — A Practical Approach to Purple Teaming in the Enterprise](https://github.com/ssnkhan/adversarial-threat-modelling) (using VECTR) can be included in your list please?

The talk contains practical guidance on how to orchestrate an intelligence led process within the Enterprise, as well as lots of tips on organising tests within VECTR. Thanks for your consideration!

**Comment by ch33r10** [comment]
Hi @ssnkhan Thank you very much for sharing your talk resources! You put a lot of work into it! I added it as a resource under VECTR!!! =)
